"""Add KnowledgeDocument and RAG tables

Revision ID: 3096b991072a
Revises: 4300c8bca77e
Create Date: 2025-12-27 20:08:22.431151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3096b991072a'
down_revision: Union[str, Sequence[str], None] = '4300c8bca77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("""
        CREATE TABLE IF NOT EXISTS document_embeddings (
            id SERIAL PRIMARY KEY,
            document_id INT REFERENCES knowledge_documents(id) ON DELETE CASCADE,
            chunk_index INT,
            chunk_text TEXT,
            embedding vector(1536)
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS document_embeddings")
    # ### end Alembic commands ###
