"""Add widget customization to ClientProfile

Revision ID: 4300c8bca77e
Revises: e7cad87e447a
Create Date: 2025-12-07 07:47:06.787600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4300c8bca77e'
down_revision: Union[str, Sequence[str], None] = 'e7cad87e447a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('widget_primary_color', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_text_color', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_bubble_color', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_user_bubble_color', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_position', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_size', sa.String(length=20), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_welcome_message', sa.String(length=200), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_enabled', sa.Boolean(), nullable=True))
    op.add_column('client_profiles', sa.Column('widget_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_profiles', 'widget_title')
    op.drop_column('client_profiles', 'widget_enabled')
    op.drop_column('client_profiles', 'widget_welcome_message')
    op.drop_column('client_profiles', 'widget_size')
    op.drop_column('client_profiles', 'widget_position')
    op.drop_column('client_profiles', 'widget_user_bubble_color')
    op.drop_column('client_profiles', 'widget_bubble_color')
    op.drop_column('client_profiles', 'widget_text_color')
    op.drop_column('client_profiles', 'widget_primary_color')
    # ### end Alembic commands ###
