"""updated user model for oauth

Revision ID: a3e41e91ba15
Revises: 46bf23c4a24d
Create Date: 2025-11-17 12:16:46.741343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e41e91ba15'
down_revision: Union[str, Sequence[str], None] = '46bf23c4a24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
