"""pan_number -> non-unique

Revision ID: b60b0361c8bb
Revises: fb6955ca83f2
Create Date: 2025-11-09 23:03:17.117456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60b0361c8bb'
down_revision: Union[str, Sequence[str], None] = 'fb6955ca83f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pan_number'), table_name='users')
    op.create_index(op.f('ix_users_pan_number'), 'users', ['pan_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_pan_number'), table_name='users')
    op.create_index(op.f('ix_users_pan_number'), 'users', ['pan_number'], unique=True)
    # ### end Alembic commands ###
