"""make phone numbers non-unique

Revision ID: f1b51a960cd7
Revises: 71f7a6bab8bc
Create Date: 2025-11-19 18:03:05.372988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b51a960cd7'
down_revision: Union[str, Sequence[str], None] = '71f7a6bab8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=True)
    # ### end Alembic commands ###
