"""Add support_hours to ClientProfile

Revision ID: f7b1cf76fa5e
Revises: 1f11d231c352
Create Date: 2025-11-07 12:09:17.607374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b1cf76fa5e'
down_revision: Union[str, Sequence[str], None] = '1f11d231c352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('primary_usecase', sa.String(length=500), nullable=True))
    op.add_column('client_profiles', sa.Column('Business_goals', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_profiles', 'Business_goals')
    op.drop_column('client_profiles', 'primary_usecase')
    # ### end Alembic commands ###
