"""minor clean-up

Revision ID: fb6955ca83f2
Revises: f7b1cf76fa5e
Create Date: 2025-11-09 20:59:47.720481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6955ca83f2'
down_revision: Union[str, Sequence[str], None] = 'f7b1cf76fa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('business_goals', sa.String(length=500), nullable=True))
    op.drop_column('client_profiles', 'Business_goals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_profiles', sa.Column('Business_goals', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('client_profiles', 'business_goals')
    # ### end Alembic commands ###
